### ISSUE TITLE
How to apply photo behind text.

### ISSUE THREAD

**Issue by josephtkim** [LeslieMcD/prj-rev-bwfs-dasmoto#2]
https://github.com/LeslieMcD/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20and%20Crafts/index.html#L9

To add an image behind the text, you can use the background-image property in CSS. Here is the corresponding HTML and CSS to implement this

HTML:
```html
<h1>Dasmoto's Arts & Crafts</h1>
```

CSS:
```css
h1 {
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
}
```

This should be all you need to accomplish this!
